### ISSUE TITLE
APP Crashes when opening settings

### ISSUE THREAD

**Issue by kumax1024** [Dar9586/NClientV2#219]
Android 5.1
APP crashes happen in version 2.4.x and higher.
Crash Report:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dar.nclientv2/com.dar.nclientv2.SettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2675)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
	at android.app.ActivityThread.access$1000(ActivityThread.java:197)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1611)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:5958)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
	at com.dar.nclientv2.components.views.GeneralPreferenceFragment.initStoragePaths(GeneralPreferenceFragment.java:4)
	at com.dar.nclientv2.components.views.GeneralPreferenceFragment.mainMenu(GeneralPreferenceFragment.java:10)
	at com.dar.nclientv2.components.views.GeneralPreferenceFragment.setType(GeneralPreferenceFragment.java:4)
	at com.dar.nclientv2.SettingsActivity.onCreate(SettingsActivity.java:11)
	at android.app.Activity.performCreate(Activity.java:6251)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2622)
	... 11 more
```

**Comment by Dar9586** [comment]
Fixed
